--创建配送地址序列号
CREATE SEQUENCE address_sequence -- address_sequence这个就是后面要用到这个序列号时引用的名称
INCREMENT BY 1　                                              -- 每次加几个
START WITH 1　　                                              -- 从1开始计数
NOMAXVALUE　　　                                              -- 不设置最大值
NOCYCLE　　　　　                                            -- 一直累加，不循环
CACHE 100;                       -- 缓存值 100

--创建出入库单据序列号
CREATE SEQUENCE bill_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建出入库单据详情序列号
CREATE SEQUENCE bill_detail_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建购买信息序列号
CREATE SEQUENCE buy_good_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建购买车信息序列号
CREATE SEQUENCE car_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建评价信息序列号
CREATE SEQUENCE evaluate_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建反馈信息序列号
CREATE SEQUENCE feedback_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建商品信息序列号
CREATE SEQUENCE good_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建客户等级序列号
CREATE SEQUENCE grade_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建群组信息序列号
CREATE SEQUENCE group_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建出入库记录序列号
CREATE SEQUENCE idepot_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建图片信息序列号
CREATE SEQUENCE image_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建邮件序列号
CREATE SEQUENCE mail_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建模块信息序列号
CREATE SEQUENCE modle_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建新闻序列号
CREATE SEQUENCE news_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建日志序列号
CREATE SEQUENCE operlog_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建订单信息序列号
CREATE SEQUENCE order_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建订单详情序列号
CREATE SEQUENCE order_detail_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建价格信息序列号
CREATE SEQUENCE price_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建招聘信息序列号
CREATE SEQUENCE recruit_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建权限信息序列号
CREATE SEQUENCE right_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建角色信息序列号
CREATE SEQUENCE role_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建统计信息序列号
CREATE SEQUENCE stat_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;
     
--创建库存信息序列号
CREATE SEQUENCE stock_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建仓库信息序列号
CREATE SEQUENCE storage_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建种类信息序列号
CREATE SEQUENCE type_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建用户信息序列号
CREATE SEQUENCE user_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建聊天信息记录表序列号
CREATE SEQUENCE chat_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;

--创建数据统计表序列号
CREATE SEQUENCE datastat_sequence
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
CACHE 100;